### ISSUE TITLE
How check associations?

### ISSUE THREAD

**Issue by evgarik** [feathersjs-ecosystem/feathers-sequelize#127]
Hi guys, Help me please.
i'am read documentation - https://sequelize.readthedocs.io/en/v3/docs/associations/#check-associations
How to execute a check on the service hook.
```
function include() {
  return function (hook) {
    const productPrice = hook.app.service('product-prices').Model;
    const currencies = hook.app.service('currencies').Model;
    const edizm = hook.app.service('edizm').Model;


    const pricesShema = { model: productPrice,
      attributes: ['price', 'price_promo', 'price_card','publish'],
      include: [
        {
          model: currencies,
          attributes: ['title', 'socr']
        },
      ]
    };

    const edizmShema = { model: edizm,
      attributes: ['title', 'detail']
    };

    let association={};
    switch (hook.method){
      case "find":
        association = { include: [edizmShema,pricesShema] };
        break;
      case "get":
        association = { include: [edizmShema,pricesShema] };
        break;
    }


    hook.params.sequelize = Object.assign(association,
      { raw: false },
      {
        attributes: [
        'id',
        'title',
        'count',
        'image',
        'detail',
        'sostav',
        'edizm_id'
      ]});

    return Promise.resolve(hook);
  }
}


module.exports = {

  before: {
    all: [include()],
    find: [],
    get: [],
    create: disallow(),
    update: disallow(),
    patch: disallow(),
    remove: disallow()
  },

  after: {
    all: [include()],
    find: [],
    get: [],
    create: disallow(),
    update: disallow(),
    patch: disallow(),
    remove: disallow()
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: disallow(),
    update: disallow(),
    patch: disallow(),
    remove: disallow()
  }
};
```

**Comment by eddyystop** [comment]
Feathers hooks work with POJO's not with DB ORM's, and your `raw: false` returns an ORM.

If you can't use `raw: true` then convert the ORM to a POJO (and back to a ORM is really needed).
`const dehydrate = require('feathers-sequelize/hooks/dehydrate');
hooks.after.find = [dehydrate(), discard('password')]`.

There is also a hydrate hook https://github.com/feathersjs/feathers-sequelize/tree/master/src/hooks

**Comment by daffl** [comment]
I think include shouldn't be registered as a before *and* after hook. If you set `raw: false` we can check the association in a custom `after` hook though (and then convert it back to a plain JavaScript object as @eddyystop suggested).

I'm going to reopen for now because I think this might be worth looking into a little more. Related Stackoverflow question: https://stackoverflow.com/questions/44593261/how-to-check-associations-feathers-sequelize-in-service-hook

**Comment by evgarik** [comment]
@daffl , Thanks for the help. I'll wait for your decision.

**Comment by DesignByOnyx** [comment]
I think this falls under the the umbrella of [working with model instances](https://docs.feathersjs.com/api/databases/sequelize.html#working-with-sequelize-model-instances). As soon as someone wants to do something sequelize-specific (such as `foo.hasUser()`), they need to instantiate the data. There are several ways to do this, and _"which one"_ depends on the situation. A recurring theme is we need to do a better job of making people aware of when to "hydrate", when to "dehydrate", when to use `raw: false`, etc. I don't mind taking this responsibility.

**Comment by musicformellons** [comment]
General idea is clear, but the [docs](https://docs.feathersjs.com/api/databases/sequelize.html#working-with-sequelize-model-instances) confuse me. The 2 ways are documented as alternatives it seems, but in the [quoted gist](https://gist.github.com/sicruse/bfaa17008990bab2fd1d76a670c3923f) they are both implemented, which is odd (and thus raises a question by someone in the gist, but it is not answered). I suppose alternative 1 (using { raw: false }) would work in both before- and after-hooks, whereas alternative 2 (hydrate (dehydrate)) works only for after-hooks!?

A 'general best practice' example would clarify a lot. For after-hooks is it as simple as hydrating before and dehydrating after each customhook (or each sequence of customhooks)? And for before-hooks the 'equivalent' is to set { raw: false } for each customhook?
