### ISSUE TITLE
Custom getter not being called properly.

### ISSUE THREAD

**Issue by subodhpareek18** [feathersjs-ecosystem/feathers-sequelize#129]
I have the following model set up in sequelize:
```js
import uid from 'uid-safe';

export default (sequelize, DataTypes) => {
  const Model = sequelize.define(
    'location',
    {
      id: {
        type: DataTypes.STRING,
        defaultValue: () => `loc_${uid.sync(6)}`,
        primaryKey: true
      },
      coordinates: {
        type: DataTypes.GEOMETRY('POINT'),
        get() {
          const value = this.getDataValue('coordinates');
          return value === null ? null : value.coordinates;
        },
        set(value) {
          if (value === null) {
            this.setDataValue('coordinates', null);
          } else {
            this.setDataValue('coordinates', {
              type: 'Point',
              coordinates: value
            });
          }
        },
        validations: {
          isCoordinateArray: value => {
            if (!Array.isArray(value) || value.length !== 2) {
              throw new Error('Must be an array with 2 elements');
            }
          }
        }
      },
    }
  );
  return Model;
};
```
Now every thing works fine when I create a record.
```js
// request
{
	"postcode": "XYZ",
	"coordinates": [-75.343, 39.984]
}
 
// response
{
	"coordinates": [
		-75.343,
		39.984
	],
	"id": "loc_Eeksy8q8",
	"postcode": "XYZ",
}
```
But when I look at the response on a `get` or `find` method the custom getter doesn't get called and I see this instead:
```js
{
	"coordinates": {
		"type": "Point",
		"coordinates": [
			-75.343,
			39.984
		]
	},
	"id": "loc_Eeksy8q8",
	"postcode": "XYZ",
}
```

### System configuration
**Module versions**:
```json
{
    "feathers": "^2.1.1",
    "feathers-sequelize": "^2.0.1",
    "pg": "^6.1.5",
    "sequelize": "^3.30.4"
}
```
**Database Setup**:
PostGreSQL 9.6
with postGIS 2.3 Bundle

**NodeJS version**:
v8.0.0

**Operating System**:
Windows 10 Pro

**Browser Version**:
Chrome Version 60.0.3112.40 (Official Build) beta (64-bit)

**Comment by zusamann** [comment]
Hi, any input on this? Sorry for being impatient.

**Comment by daffl** [comment]
Setting `raw: false` in the options should solve your issue.

**Comment by DesignByOnyx** [comment]
@zusamann - I can confirm. By default, we set `raw: true` because 1) it's more efficient - way less processing overhead, and 2) it allows feathers-sequelize to work with common hooks and other 3rd party integrations out of the box. If you are needing something which is specific to sequelize (such as getters and setters), you will indeed need to [follow this part of the guide](https://docs.feathersjs.com/api/databases/sequelize.html#working-with-sequelize-model-instances). I just submitted a [PR](https://github.com/feathersjs/feathers-docs/pull/783) to update the guides and make this more prevalent.

**Comment by knoxcard** [comment]
Heard a fix is in the works.  When it will be released? unknown, but sounds like within the next 6 months or so.

**Comment by sharadshetty2** [comment]
> Setting `raw: false` in the [service options](https://docs.feathersjs.com/api/databases/sequelize.html#serviceoptions) should solve your issue.

I'm using the sequelize migrations.I've gone through the feathersjs link provided still I've no idea where to pass the option raw:false.

**Comment by daffl** [comment]
In the `options` of `src/services/<name>/<name>.service.js` (e.g. https://github.com/feathersjs/feathers-chat/blob/master/src/services/users/users.service.js#L10)

**Comment by sharadshetty2** [comment]
I'm using the project structure created by sequelize-cli. ( https://sequelize.org/v5/manual/migrations.html)
