### ISSUE TITLE
Allow hydrated instances to enter into the adapter

### ISSUE THREAD

**Issue by DesignByOnyx** [feathersjs-ecosystem/feathers-sequelize#131]
This covers situations where a user might want to instantiate a model in the "before" phase of a service. This is useful if a user wants to trigger getters/setters/validations and/or using the `hydrate` hook in the "before" phase. There may be other use cases where a user instantiates an ORM model and it should not cause the service fail. Furthermore, the same exact model instance should be returned.

**Comment by DaddyWarbucks** [comment]
This is an interesting idea. But I am not sure how useful it is in the latest version (2024 , V8). I also think the service methods would be confused what to do with an instance. Just save it? Add data and save it? Etc.

If a developer wants to work with models directly, they can do so and then skip the service method by manually setting the result.

```js
const myHook = async (context) => {
  const myInstance = new Model(context.data);
  myInstance.set(data);
  await myInstance.save();
  context.result = myInstance;
  return context;
}
```
