### ISSUE TITLE
original Error is not kept as data of returned FeathersError

### ISSUE THREAD

**Issue by ramsestom** [feathersjs-ecosystem/feathers-sequelize#148]
in utils.js, the errorHandler function should be changed to
```
function errorHandler(error) {
  var feathersError = error;

  if (error.name) {
    switch (error.name) {
      case 'SequelizeValidationError':
      case 'SequelizeUniqueConstraintError':
      case 'SequelizeExclusionConstraintError':
      case 'SequelizeForeignKeyConstraintError':
      case 'SequelizeInvalidConnectionError':
        feathersError = new _feathersErrors2.default.BadRequest(error.message, error);
        break;
      case 'SequelizeTimeoutError':
      case 'SequelizeConnectionTimedOutError':
        feathersError = new _feathersErrors2.default.Timeout(error.message, error);
        break;
      case 'SequelizeConnectionRefusedError':
      case 'SequelizeAccessDeniedError':
        feathersError = new _feathersErrors2.default.Forbidden(error.message, error);
        break;
      case 'SequelizeHostNotReachableError':
        feathersError = new _feathersErrors2.default.Unavailable(error.message, error);
        break;
      case 'SequelizeHostNotFoundError':
        feathersError = new _feathersErrors2.default.NotFound(error.message, error);
        break;
    }
  }

  throw feathersError;
}
```

so that the original Sequelize error is kept has data in the returned feathersError.
This is not a breaking change, this just allows to keep the original Sequelize error as data (because for now, this information is lost. Indeed, only error.message would be kept as feathersError.message if feathersError is created with error as unique argument of feathersError(message, data) constructor ) 
I tested this change locally on my feathers.js server and everyting works fine

**Comment by daffl** [comment]
That makes sense although, could that error contain sensitive information about your database setup though?

**Comment by ramsestom** [comment]
yeas. already discussed this with ryan wheale on slack: https://feathersjs.slack.com/conversation/C0HJE6A65/p1502220782871848
the database scheme can be exposed as sequelize error contains the sql query that produced the error.
we agreed to grab the minimum amount of useful information from the sequelize error and create a new object before passing it to the feathersError constructor. This should also be done before `var feathersError = error;` as for now, if it is not an error handled by the switch case, the original sequelize error (that contains the sql query) is directly thrown by feathers...

**Comment by andrewmunro** [comment]
I agree, this is handled badly. The error message is passed through without any context of the original error, making it hard to programatically filter out DB errors from standard application ones.

For example, if my db credentials are invalid the error will be a 403 and the message is `Access denied for user \'redacted\'@\'redacted\' (using password: YES)`.

How can I tell this is a db error besides matching the error.message?

**Comment by louim** [comment]
Hey! I encountered the opposite problem when running validations from the model. Here is an example response:

```
{
    "name": "BadRequest",
    "message": "Validation error: Validation isIn on role failed",
    "code": 400,
    "className": "bad-request",
    "errors": [
        {
            "message": "Validation isIn on role failed",
            "type": "Validation error",
            "path": "role",
            "value": "ts",
            "origin": "FUNCTION",
            "instance": {
                "id": null,
                "externalId": "26",
                "roomId": "77082fc3-cb04-4dc9-ac79-4892209a4abb",
                "displayName": "louim",
                "role": "ts",
                "updatedAt": "2017-12-07T21:10:24.896Z",
                "createdAt": "2017-12-07T21:10:24.896Z"
            },
            "validatorKey": "isIn",
            "validatorName": "isIn",
            "validatorArgs": [
                [
                    "admin",
                    "moderator",
                    "user"
                ]
            ],
            "__raw": {
                "validatorName": "isIn",
                "validatorArgs": [
                    [
                        "admin",
                        "moderator",
                        "user"
                    ]
                ]
            }
        }
    ]
}
```

This is bad because it exposes the instance which may contain sensitive data. There should definitively be a normalization job done by `feathers-sequelize` before passing the error to `feathers-errors`.

**Comment by TimNZ** [comment]
+1 

Just spent some time debugging on why a BadRequest was being thrown after an insert and see in util.js that none of the error info is being passed in as data.

How do we rapidly make a decision on what is a good set of starting data that is safe to be passed back, and possibly consistent structure with other DB wrappers.

**Comment by JulienPapini** [comment]
+1

I want to parse BadRequests thrown by feathers-sequelize.
For the ForeignKeyConstraintError, "SQLITE_CONSTRAINT: FOREIGN KEY constraint failed" is not really a good error message.
And for validation errors, there are a lot of sensitives datas as @louim said.

**Comment by daffl** [comment]
Processing error messages is what [Feathers error hooks](https://docs.feathersjs.com/api/hooks.html) are for which give you the flexibility to return the error in a format you want.

I'd accept a pull request that deals with this in a consistent manner from someone who is more familiar with Sequelize than me.

**Comment by TimNZ** [comment]
@JulienPapini agree with @daffl that feathers-sequelize should return errors as is and you can modify what you do and return in the after/error hooks.

The simplicity and hookiness of the hooks system is a winner feature of Feathers, making it really easy to build microservices that consume each other and slot into a pipeline.

**Comment by JulienPapini** [comment]
I already do a hooks for formatting validations errors:
```
const { checkContext } = require('feathers-hooks-common')
const Sequelize = require('sequelize')

function formatValidationErrorItem (context) {
  const errors = {}

  for (const error of context.error.errors) {
    if (!(error instanceof Sequelize.ValidationErrorItem)) return context
    if (!errors[error.path]) errors[error.path] = []
    errors[error.path].push(error.message)
  }

  context.error.message = 'Validation error'
  context.error.errors = errors

  return context
}

module.exports.formatError = function () {
  return context => {
    checkContext(context, 'error')

    if (Array.isArray(context.error.errors) &&
      context.error.errors.length > 0 &&
      context.error.errors[0] instanceof Sequelize.ValidationErrorItem
    ) {
      return formatValidationErrorItem(context)
    }
  }
}
```

It check if items in `context.error.errors` are instance of `Sequelize.ValidationErrorItem` and then formatting it.

`context` before:
```
{
  type: 'FeathersError',
  name: 'BadRequest',
  message: 'User id already exists',
  code: 400,
  className: 'bad-request',
  data: undefined,
  errors: 
   [ ValidationErrorItem {
       message: 'User id already exists',
       type: 'unique violation',
       path: 'user_id',
       value: 'a8fa24e5-da1c-4c82-b48e-55ba84ad5c49',
       origin: 'DB',
       instance: [user_passwords],
       validatorKey: 'not_unique',
       validatorName: null,
       validatorArgs: [] } ] }
```

`context` after:
```
{
  type: 'FeathersError',
  name: 'BadRequest',
  message: 'Validation error',
  code: 400,
  className: 'bad-request',
  data: undefined,
  errors: { user_id: [ 'User id already exists' ] } }
```

But I have also foreign key constraints in my models and sometimes I have this error:
```
{
  type: 'FeathersError',
  name: 'BadRequest',
  message: 'SQLITE_CONSTRAINT: FOREIGN KEY constraint failed',
  code: 400,
  className: 'bad-request',
  data: undefined,
  errors: {} }
```

And there are no ways to check is this error is an instance of `ForeignKeyConstraintError` for doing appropriate formatting :(

**Comment by TimNZ** [comment]
Fair call.  The @feathersjs/errors FeathersError function should stick the passed error object into a 'originalError' property perhaps when message = Error object

```
const debug = require('debug')('@feathersjs/errors');

function FeathersError (msg, name, code, className, data) {
  msg = msg || 'Error';
 
  let errors;
  let message;
  let newData;

  if (msg instanceof Error) {
    message = msg.message || 'Error';
    this.originalError = msg
```
