### ISSUE TITLE
Unflatten results of raw queries

### ISSUE THREAD

**Issue by DesignByOnyx** [feathersjs-ecosystem/feathers-sequelize#149]
Sequelize will not process the results of raw queries. This becomes a problem with eager loading as the data returned from the underlying db engine looks like this:

```
{
  'id: 1,
  'foo': 'bar',
  'user.id': 222,
  'user.name': 'David'
}
```

This should be converted into a nested structure:

```
{
  'id: 1,
  'foo': 'bar',
  'user': {
    'id': 222,
    'name': 'David'
  }
}
```

Unfortunately, the method which does the nesting is "_private", and the [techniques used within the method](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1581) will not work on "raw" data. Thus, there are two solutions:

1. Set `raw: false` whenever eager loading is happening. And then serialize the results into a POJO.
    - **pros:** will let sequelize do the nesting
    - **cons:** sequelize is instantiating all of the data just for the sake of nesting it. This is not very efficient and loses the performance gains of "raw" queries.
2. We write a nesting function ourselves. 
    - **pros:** maintains the performance gains of nested queries.
    - **cons:** will use slightly different technique than sequelize internals and could cause unforeseen problems? 

My vote is for `#2`, as I think it will work for 99% of cases. Those who experience the unexpected can use `raw: false`. I would make a note about this in the docs.

**Comment by zusamann** [comment]
Wanted to chime in with one point, when the nested value is let's say an array of objects, then currently while flattening, the result only contains the first value of the array and ignores everything else, which is obviously a `major` issue. 

This is one of the reasons why we had to use `raw:false` everywhere.

**Comment by DesignByOnyx** [comment]
Eesh - that hurts! I will verify that first - but I trust you. If what you say is true, then Option 1 is our only option, which sucks.

**Comment by daffl** [comment]
I'm starting to feel that at least with Sequelize we seem to be having just as many issues with `raw: true` as we had with `raw: false`.

**Comment by zusamann** [comment]
I'm simply using this as a first hook on all db services. 
```
import R from 'ramda';

export const toJSON = () => ctx => {
  if (
    R.type(ctx.result.data) === 'Array' &&
    R.type((ctx.result.data[0] || {}).toJSON) === 'Function'
  ) {
    ctx.result.data = ctx.result.data.map(r => r.toJSON());
  } else if (R.type(ctx.result.toJSON) === 'Function') {
    ctx.result = ctx.result.toJSON();
  }
  return ctx;
};
```
And this has kind of solved all my problems with hooks. Granted I've not used a lot of hooks so far.

Apart from the perf issues, and issues with hooks (which can be solved with above), is there anything else that's guiding us to use `raw: false` as default?

**Comment by FreeLineTM** [comment]
`raw: false` works fine, but `context.result` and `context.dispatch` contains data that is hard to work with.

**Comment by kingmatusevich** [comment]
There really is a need for this to be fixed. I can't understand why this is still an issue.

**Comment by daffl** [comment]
This is actually not an issue anymore and the solution has been documented in the [working with model instances section](https://github.com/feathersjs-ecosystem/feathers-sequelize#working-with-sequelize-model-instances)
