### ISSUE TITLE
Sequelize connection works for GET but not POST on standard service?

### ISSUE THREAD

**Issue by georgeedwards** [feathersjs-ecosystem/feathers-sequelize#159]
### Steps to reproduce

Follow the [Chat](https://docs.feathersjs.com/guides/chat/readme.html) guide, but use sequelize rather than the default db. I am using a local SQL Server 2016 instance, this is what my sequelize object looks like:

```
  const sequelize = new Sequelize('feathers_backend', null, null, {
    dialect: 'mssql',
    dialectModulePath: 'sequelize-msnodesqlv8',
    logging: false,
    dialectOptions: {
      driver: 'SQL Server Native Client 11.0',
      instanceName: 'MSSQLSERVER01',
      trustedConnection: true,
    }
  });
```
I got as far as creating the messages API and downloading the postman HTTP examples. 

### Expected behavior
The application to work as described in the guide - i.e. regular CRUD behaviour.

### Actual behavior
POSTing new messages works fine, with the expected result returned. However, as soon as I do a GET, I get this error:

> info: after: messages - Method: create
info: after: messages - Method: create
info: error: messages - Method: find: [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near 'OFFSET'.
error:  SequelizeDatabaseError: [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near 'OFFSET'.
    at Query.formatError (C:\Users\George\Source\Repos\feathers-app\node_modules\sequelize\lib\dialects\mssql\query.js:322:12)
    at Request.connection.lib.Request [as callback] (C:\Users\George\Source\Repos\feathers-app\node_modules\sequelize\lib\dialects\mssql\query.js:107:25)
    at Connection.removeRequest (C:\Users\George\Source\Repos\feathers-app\node_modules\sequelize-msnodesqlv8\lib\connection.js:173:13)
    at context.connection.queryRaw (C:\Users\George\Source\Repos\feathers-app\node_modules\sequelize-msnodesqlv8\lib\request.js:31:14)
    at routeStatementError (C:\Users\George\Source\Repos\feathers-app\node_modules\msnodesqlv8\lib\driverRead.js:20:7)
    at C:\Users\George\Source\Repos\feathers-app\node_modules\msnodesqlv8\lib\driverRead.js:204:13
    at Object.cbFreeStatement [as end] (C:\Users\George\Source\Repos\feathers-app\node_modules\msnodesqlv8\lib\driverMgr.js:202:7)

### System configuration

**Module versions** (especially the part that's not working):
```
    "feathers": "^2.2.0",
    "feathers-authentication": "^1.2.7",
    "feathers-authentication-hooks": "^0.1.4",
    "feathers-authentication-jwt": "^0.3.2",
    "feathers-authentication-local": "^0.4.4",
    "feathers-configuration": "^0.4.1",
    "feathers-errors": "^2.9.1",
    "feathers-hooks": "^2.0.2",
    "feathers-hooks-common": "^3.7.2",
    "feathers-rest": "^1.8.0",
    "feathers-sequelize": "^2.3.0",
    "feathers-socketio": "^2.0.0",
    "helmet": "^3.8.1",
    "sequelize": "^4.8.0",
    "sequelize-msnodesqlv8": "^0.2.6-beta.5",
```

**NodeJS version**: 6.11.2

**Operating System**: Windows 10 Pro

**Comment by georgeedwards** [comment]
NB, this is the generated SQL statement - `Executing (default): SELECT [id], [text], [createdAt], [updatedAt] FROM [messages] AS [messages] OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;`

**Comment by DesignByOnyx** [comment]
It appears that "ORDER" is required when using OFFSET/FETCH: https://technet.microsoft.com/en-us/library/gg699618(v=sql.110).aspx

Can you see what happens if you sort by "createdAt"? If you were [following the guides](https://docs.feathersjs.com/guides/chat/frontend.html#connecting-to-the-api), your front end code would look like this:

```
messages.find({ $sort: { 'createdAt': -1 }).then(...);
```
