### ISSUE TITLE
SequelizeDatabaseError not handled after upgrading to Sequelize 4.x.x

### ISSUE THREAD

**Issue by galioy** [feathersjs-ecosystem/feathers-sequelize#165]
### Steps to reproduce
I've got a custom hook that initializes my Sequelize instance and the DB connections. I upgraded the version of the Sequelize instance used there from `3.30.4` to `4.8.4`, and in [the tutorial for upgrading to `v4`](http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html#breaking-changes) it says that _Sequelize now uses an independent copy of bluebird library_. 

Now my Feathers services that use a Sequelize connection do not get their errors handled. Well, and the actual calls to the Sequelize instance are under the hood, so the only place for me to customly handle the errors is in the `errors` hook of each service, but that will only handle it for the final response. I still get the errors spewed in my console (and thus when I run automated tests).

I checked the version of Sequelize in the `feathers-sequelize` that I use, and it's `^4.3.0`, which means the Promise thing should be compatible already, right?

I am a bit confused here and not sure what and where should I change in order to get the errors handled instead of puked out in my terminal.

**Module versions** (especially the part that's not working):
`~2.1.0`
**NodeJS version**:
`6.11.1`
**Operating System**:
OS X El Capitan

**Comment by DesignByOnyx** [comment]
I am a little unclear as to the problem you are experiencing. Can you answer the following:

1. Are you able to handle sequelize errors at all?
2. Are you mostly concerned with getting rid of the console logging? I don't really recommend this (per the recommendations of the [12 factor app](https://12factor.net/logs)).
3. Would you be willing to create a simple app which reproduces the problem? It's way easier for us to fix things if we don't have to spend time trying to recreate it.
