### ISSUE TITLE
Support for Master / Replica setups?

### ISSUE THREAD

**Issue by coreh** [feathersjs-ecosystem/feathers-sequelize#174]
Hey there!

I've been working on [a fork of `feathers-sequelize` that supports multiple sequelize instances](http://github.com/coreh/feathers-sequelize-replicated): One master instance and several replica instances, with all write queries going into the master, and all read queries going into the replicas. This goes hand in hand with our usage of PostgreSQL 10 which now supports logical replication.

Right now my approach is kinda hacky and too tied to our specific setup, but I'd like to know if there would be interest in adding this sort of functionality to `feathers-sequelize`, possibly through some sort of "routing" callback to dynamically decide which sequelize instance to send the queries to depending on their nature. If so, I'd be happy to open a pull request.

Thanks in advance.

**Comment by DesignByOnyx** [comment]
This is amazing! I didn't read through all the code, but I would love to review a PR and go through some things. For example, stuff I noticed immediately:

- don't make `options.master` required. If people are using replica sets, they will set it.
- allow more control in `decideServer` - right now you use random, but we should consider others like round-robin, sticky?, etc.

I would use this immediately, on a rather big client too!

**Comment by coreh** [comment]
Hooray! I'm updating my fork to get it up to date with the mainline `feathers-sequelize` branch (It's already quite out of date) and I'll open a pull request so that we can work these out.

**Comment by TimNZ** [comment]
+1
