### ISSUE TITLE
How to work with the relationship from URL query?

### ISSUE THREAD

**Issue by vodniciarv** [feathersjs-ecosystem/feathers-sequelize#176]
I will read [the quering documentation](https://docs.feathersjs.com/api/databases/querying.html).
For example:
`GET /category?$select[]=parent&$select[]=icon`
select columns `parent` and `icon` from `category`

Now if the `category` model have a relation with `translate` model, how to select columns from the `translate` model from URL? 

![screenshot_4](https://user-images.githubusercontent.com/14403446/32525157-b71ab5fe-c42b-11e7-97aa-caebf3545ee6.png)

**Comment by DesignByOnyx** [comment]
You need to pass this in the "include" statement:

```
hook.params.sequelize = {
  include: [{ model: translate, attributes: ['name', 'alias'] }]
}
```

Unfortunately, feathers cannot do this for you. You would need to write the code so you could do a query like this:

```
GET GET /category?$select[]=parent&$select[]=icon&$select[]=translate.name&$select[]=translate.alias
```

Here is some code to get you started:

```js
function (hook) {
  const $select = hook.params.query.$select;
  // first, remove any fields with a dot in the name from the "top level" $select
  hook.params.query.$select = $select.filter(f => f.indexOf('.') === -1);
  const translateAttrs = $select.filter(f => f.indexOf('translate.') === 0).map(f => f.replace('translate.', '');
  hook.params.sequelize = {
    include: [{ model: translate, attributes: translateAttrs }]
  };
  return hook;
}
```

**Comment by DesignByOnyx** [comment]
Closing as this is already supported (albeit manual). Please ask further questions in the [#sequelize](https://feathersjs.slack.com/messages/C42911N5U) room in Slack.

**Comment by vodniciarv** [comment]
@DesignByOnyx thank you very much.
Your code from answer works perfectly!

**Comment by khushirana** [comment]
how to implement one to many relationship between usermodel and moviemodel. where users can have many movie with it. can anyone help??
