### ISSUE TITLE
"error:  NotFound: No record found for id" when calling with socket.io

### ISSUE THREAD

**Issue by jaslocum** [feathersjs-ecosystem/feathers-sequelize#179]
This code change avoids the above error in my app:

https://github.com/feathersjs-ecosystem/feathers-sequelize/commit/9ece87ec032b95d18159e1ff39f891d948ddd02b

**Comment by daffl** [comment]
Maybe @MichaelErmer has some more insights into this.

**Comment by MichaelErmer** [comment]
Can you this a bit more? I don't see how this could cause the error, as `!==` already does a type sensitive check.
What is the error you get?

**Comment by DesignByOnyx** [comment]
I agree that the change you've suggested is not correct - while it may cause the error to go away in your app, it's not fixing the problem.

The real problem is to figure out why "id" is not defined when this code runs:

```
return _this2._getOrFind(id, findParams);
```

@jaslocum Can you please investigate since you are able to produce the error. Remove the code you added and try to see what the value of "id" is. I recommend turning on logging on the sequelize adapter so you can inspect the queries:

```
new Sequelize(connectionString, {
    dialect: 'postgres',
    logging: console.log,
    define: {
      freezeTableName: true
    }
  });
```

**Comment by JulienPapini** [comment]
The problem is due to the `$in` query parameters in the `patch` function.

Solved this error by setting up `operatorsAliases` in the sequelize configuration as explained here [http://docs.sequelizejs.com/manual/tutorial/querying.html#operators-security](url):

```
const Op = Sequelize.Op;
const operatorsAliases = {
    $eq: Op.eq,
    $ne: Op.ne,
    $gte: Op.gte,
    $gt: Op.gt,
    $lte: Op.lte,
    $lt: Op.lt,
    $not: Op.not,
    $in: Op.in,
    $notIn: Op.notIn,
    $is: Op.is,
    $like: Op.like,
    $notLike: Op.notLike,
    $iLike: Op.iLike,
    $notILike: Op.notILike,
    $regexp: Op.regexp,
    $notRegexp: Op.notRegexp,
    $iRegexp: Op.iRegexp,
    $notIRegexp: Op.notIRegexp,
    $between: Op.between,
    $notBetween: Op.notBetween,
    $overlap: Op.overlap,
    $contains: Op.contains,
    $contained: Op.contained,
    $adjacent: Op.adjacent,
    $strictLeft: Op.strictLeft,
    $strictRight: Op.strictRight,
    $noExtendRight: Op.noExtendRight,
    $noExtendLeft: Op.noExtendLeft,
    $and: Op.and,
    $or: Op.or,
    $any: Op.any,
    $all: Op.all,
    $values: Op.values,
    $col: Op.col
};

const sequelize = new Sequelize(connectionString, {
    dialect: 'sqlite',
    logging: false,
    define: {
        freezeTableName: true
    },
    operatorsAliases: operatorsAliases
});
```

**Comment by MichaelErmer** [comment]
No, https://github.com/feathersjs-ecosystem/feathers-sequelize/issues/179#issuecomment-357520085 is a different issue.
