### ISSUE TITLE
Populate joined table on create

### ISSUE THREAD

**Issue by kerimdragolj** [feathersjs-ecosystem/feathers-sequelize#180]
I have 2 models in many to many relationship, so it has joined table. Users and Events, event_participants(joined table). So when im creating event i wanna populate this joined table with event id and ids of all users that i pass in request. For some reason it is trying to create users instead of just adding their ids. How to fix this? So on create need to populate joined table?

```
events.belongsTo(models.users, {
      foreignKey: {
        name: 'creatorId',
        allowNull: false
      },
      onDelete: 'CASCADE',
      as: 'creator'
    });
    events.belongsToMany(models.users, {
      through: 'event_participants',
      as: 'participants',
      foreignKey: 'eventId',
      otherKey: 'userId'
    });
    models.users.belongsToMany(events, {
      through: 'event_participants'
    });

  }
```

**Comment by DesignByOnyx** [comment]
You would do this in a `before` hook by setting the "include" option. Please read about [sequelize associations](http://docs.sequelizejs.com/manual/tutorial/associations.html) for implementation details. Your hook will eventually look like this:

```js
function (hook) {
  hook.params.sequelize = {
    include: [ /* put your includes here - read the sequelize docs */ ]
  };
  return hook;
}
```

**Comment by DesignByOnyx** [comment]
Closing as this is already supported. Please ask questions in the [#sequelize](https://feathersjs.slack.com/messages/C42911N5U) room in slack.

**Comment by kerimdragolj** [comment]
Yes i did that, and it doesnt work for many to many relationship.. i had to make separate service which is used just to populate joined table. So when i need to do this i always have to make 2 requests, one on route of object im creating and other one to populate joined table..

**Comment by kerimdragolj** [comment]
In case anyone needs this later i found solution for this 

function includeParticipants(hook) {
    if (hook.data.workers) {
        let participants = [hook.data.participants]; //convert data form request to array.
        participants.forEach((el) => {
            hook.result[0].setWorkers(el);
        });
    }
    return hook;
}

And i call this function in after hooks on create and patch like:: 

after: {
        all: [],
        find: [],
        get: [],
        create: [
            hook => includeWorkers(hook),
        ],
        update: [],
        patch: [
            hook => includeWorkers(hook),
        ],
        remove: []
    },

wish i knew this earlier.

**Comment by foadyousefi** [comment]
Thanks @kerimdragolj Your solution worked for me also. But for anyone else reading this issue in the future, don't forget to pass `raw: false` to `context.params.sequelize`. Because if `raw: true`, sequelize not adding the extra methods to associations.

**Comment by ingeniousambivert** [comment]
@kerimdragolj, @foadyousefi 
Hey there, I am getting a TypeError: hook.result.setUsers is not a function, I logged the params.sequelize, and I have { raw: false }, also logged the hook.result it is a sequelize object. Any idea as to what might be causing this?
My hooks are very similar to yours. 
Are there any other solutions to this, plus I couldn't find appropriate documentation for this. Is there any documentation for m:n relationships in feathers-sequelize?
