### ISSUE TITLE
sequelize version 4.35 not permit $in

### ISSUE THREAD

**Issue by joacub** [feathersjs-ecosystem/feathers-sequelize#193]
```js
const findParams = Object.assign({}, params, {
          query: { [this.id]: { $in: idList } }
        });

```
** $in**
this is not permit in new versions of sequelize

**Comment by daffl** [comment]
https://github.com/feathersjs-ecosystem/feathers-sequelize/pull/194 passed with v4.36.1 and that functionality is being tested as well. If you did not use the latest CLI you may have to set up [operator aliases](https://github.com/feathersjs/generator-feathers/blob/master/generators/connection/templates/sequelize.js#L3).

**Comment by joacub** [comment]
yes sure, but you need change this to the lates version, for security reasons and performance
