### ISSUE TITLE
Searching in nested associations

### ISSUE THREAD

**Issue by matbalazsi** [feathersjs-ecosystem/feathers-sequelize#199]
Hi,

I am still not sure if this is an issue specific to feathers-sequelize or sequelize itself: 
I am trying to create a search function for my  sequelize postgresql database. A lesson (‘lesson-sql’ model) belongsTo a client and a professor (both of type ‘person-sql’). Every ‘person-sql’ has a name and belongsToMany phone-sql models through ptr-person-phone-sql.

My objective is to search for lessons where either the clients’ or the professors’ name are equal to "George".

### Steps to reproduce
The example below works well
```

  hook.params.sequelize = {
      where:{
        $or:[
          {"$client.name$":"George"},
          {"$professor.name$":"George"},
        ]
      },
      include: [
        {
          model: sequelize.models['person-sql'],
          as:'client',
        },
        {
          model: sequelize.models['person-sql'],
          as:’professor’,
        },
     ],
      raw:false
     };

```

However, when we include the phones of the client, we get the message 
### missing FROM-clause entry for table \"client\"" 

  ```
hook.params.sequelize = {
      where:{
        $or:[
          {"$client.name$":"George"},
          {"$professor.name$":"George"},
        ]
      },
      include: [
        {
          model: sequelize.models['person-sql'],
          as:'client',
           include: [
            {
              model: sequelize.models['phone-sql'],
              through: sequelize.models['ptr-person-phone-sql’],
              as:'phones',
             },

          ]
        },
        {
          model: sequelize.models['person-sql'],
          as:’professor’,
          include: [
             {
              model: sequelize.models['phone-sql'],
               through: sequelize.models['ptr-person-phone-sql’],
               as:'phones',
             },
           ]
        },
     ],
      raw:false
     };

```
### System configuration

**Module versions** :
`"feathers": "^2.2.3",
    "feathers-rest": "^1.8.0",
    "feathers-sequelize": "^3.0.0",

**NodeJS version**: 6.11.1

**Operating System**: macOSX 10.12.5

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by edwardmsmith** [comment]
I believe that this is the result of this bug:  https://github.com/sequelize/sequelize/issues/5680
