### ISSUE TITLE
Question about executing sql string using feathers-sequelize

### ISSUE THREAD

**Issue by HarisHashim** [feathersjs-ecosystem/feathers-sequelize#208]
First of all I have no idea whether this question make sense or not as I am a noob when it comes to JS and ORM.

However, I do have old codebase that have a lot of sql string query and will be faster to use em (rather than ORM) first and maybe to use ORM later.

So the question is. Since sequelize itself allow the use of RAW SQL query (as in [this link](http://sequelize.readthedocs.io/en/2.0/docs/raw-queries/)). How to use this raw SQL querying is feathers-sequelize?

Thanks and will really appreciate your reply!

**Comment by bertho-zero** [comment]
You have a section on this on the readme: https://github.com/feathersjs-ecosystem/feathers-sequelize#sequelize-raw-queries

**Comment by HarisHashim** [comment]
Is there sample code on how to do raw sql string query?

In the sequelize doc link I refer in first post. Let say this code:

```
sequelize.query("SELECT * FROM `users`", { type: sequelize.QueryTypes.SELECT})
  .then(function(users) {
    // We don't need spread here, since only the results will be returned for select queries
  })
```

Where should I put this code?

And, I might be mistaken. But the section  on that readme looks like writing about something else.

TIA

**Comment by bertho-zero** [comment]
This is the basic use of feathers queries, you do not need to implement this code:
https://docs.feathersjs.com/guides/basics/databases.html
https://docs.feathersjs.com/api/databases/querying.html

**Comment by HarisHashim** [comment]
So can not use feathers-sequelize to query database using SQL string? Looks like it just works as ORM even though the underlying library (sequalize) allow raw SQL string query.

**Comment by bertho-zero** [comment]
I guess you want to use that in a hook, like this: https://github.com/feathersjs-ecosystem/feathers-sequelize#paramssequelize
```js
app.service('messages').hooks({
  before: {
    async find(context) {
      // Get the Sequelize instance. In the generated application via:
      const sequelize = context.app.get('sequelizeClient');

      const result = await sequilize.query( /**/ );
    }
  }
});
```

Otherwise you should extend the service and replace the desired method.
From `require('feathers-sequelize').Service`

**Comment by HarisHashim** [comment]
Thanks, exactly the solution I am looking for. Closing this question!

**Comment by musicformellons** [comment]
@HarisHashim I am having the exact same issue: want to use sequelize.query to run raw sql via sequelize in feathersjs. My questions:
- Could you share more about your hook maybe? 
- What I do not get from above: so far my hooks end with `return Promise.resolve(hook)`  the above does not... Makes me wonder 'where does `result` go to' in the above example?

**Comment by DesignByOnyx** [comment]
The way feathers services work is like this:

> beforehook1 -> beforehook2 -> **[DATA STORE]** -> afterhook1 -> afterhook1

In the case of feathers-sequelize, the DATA STORE is some SQL database. With any feathers service, you can skip the [DATA STORE] step by setting `hook.result` in a before hook. To bring this full circle, you should create a before hook like this for executing custom SQL queries:

```js
(context) => {
  const sequelize = context.app.get('sequelizeClient');
  if (shouldUseRawQuery) {
    return sequelize.query('SELECT ...').then(results => {
      context.results = results; // this tells feathers to skip the DATA STORE step above
      return context; // always resolve the promise chain with the context
    });
  }
}
```

**Comment by musicformellons** [comment]
@DesignByOnyx Thanks for the explanation. I think you mean `context.result = results; `

**Comment by chetan-alef** [comment]
The method works. But i'm having a difficult time writing hook tests. When the test runs and it gets to `sequelize.query`, I get the following error. `TypeError: Cannot read property 'query' of undefined`. Can someone help me with this issue? Thanks.
