### ISSUE TITLE
Question: Feathers Sequelize raw query and feathers service without using model.

### ISSUE THREAD

**Issue by HarisHashim** [feathersjs-ecosystem/feathers-sequelize#215]
I asked question before about using feathers service hook to do raw query.

But all example show how to build model and use that model  in service.

Is it possible and and if possible, how to use Feathers Sequelize without having a model? Or at least by defining model that is not saved in database as a table.

TIA
HARIS

**Comment by daffl** [comment]
Models are how Sequelize works but it allows to do raw queries as [documented here](http://docs.sequelizejs.com/manual/tutorial/raw-queries.html). They can be used directly in any [standard custom Feathers service](https://docs.feathersjs.com/guides/basics/services.html).

**Comment by HarisHashim** [comment]
Thanks @daffl 

Followed your advise and manage to make it work. Closing this issue/question.

**Comment by stormmuller** [comment]
@daffl is there a way we can use the feathers-sequelize generated service for all the service methods except one? For example: create, update, and remove all handled by sequelize-feathers and we create a standard custom feathers service to handle the find method.

**Comment by daffl** [comment]
Yes. [Extend the service class](https://docs.feathersjs.com/api/databases/common.html#classes-es6) and override the custom methods with your own functionality.
