### ISSUE TITLE
Fix bug Pg-Native

### ISSUE THREAD

**Issue by ricardopolo** [feathersjs-ecosystem/feathers-sequelize#222]
My API is not working because sequelize throw errors searching for module "pg-native"

<img width="1141" alt="screen shot 2018-07-11 at 8 44 23 pm" src="https://user-images.githubusercontent.com/1263856/42607986-456016fc-854b-11e8-98c8-4a1ec639e7be.png">

Do you have reports of this issue? it only start to happens when I migrated Postgres from mysql.

There is an Issue here https://github.com/sequelize/sequelize/issues/3781
And there is a solution https://github.com/sequelize/sequelize/pull/9551

Can you please update this package to apply the solution released in the latest version of sequelize?

Thanks!!

**Comment by daffl** [comment]
If you migrate from one database to another in an existing you will have to install the new database driver yourself. A simple `npm i pg --save` or `npm i pg-native --save` should do it.

**Comment by ricardopolo** [comment]
Hi daft. I did it. I also remove the package relate to the other db. 

I thing definitely is this bug. The message is exactly as I see.

**Comment by ricardopolo** [comment]
The issue was caused when the server have a performance issue, and start to consume 100% of CPU.

**Comment by lxcid** [comment]
I have the exact same issue, did u resolve it?

**Comment by DesignByOnyx** [comment]
Since this only happens in certain situations, the "fix" will not be implemented in feathers. I have used the following code with success on one of my projects that experienced the issue. Put this at the top of your main app.js file:

```js
var pg = require('pg');
delete pg.native;
```
