### ISSUE TITLE
Find & include data structure shape

### ISSUE THREAD

**Issue by EmirGluhbegovic** [feathersjs-ecosystem/feathers-sequelize#224]
I have a roles model and a permissions model.
In the roles model I have:
roles.belongsToMany(models.permissions, { through: 'rolePermissions' });

Then in the roles hook I have the following function that runs in the Before.Find Hook
```js
const attachAssociations = (context) => {
  // Get the Sequelize instance. In the generated application via:
  const sequelize = context.app.get('sequelizeClient');
  const { permissions } = sequelize.models;
  context.params.sequelize = {
    include: [permissions]
  }
  return context;
}
```
When I do a request then to users I get the following output:
```js
{ total: 1,
  limit: 10,
  skip: 0,
  data: 
   [ { id: 1,
       name: 'anonymous',
       createdAt: 2018-07-18T06:13:29.971Z,
       updatedAt: 2018-07-18T06:13:29.971Z,
       'permissions.id': 2,
       'permissions.name': 'create-user',
       'permissions.createdAt': 2018-07-18T06:13:29.895Z,
       'permissions.updatedAt': 2018-07-18T06:13:29.895Z,
       'permissions.rolePermissions.createdAt': 2018-07-18T06:13:29.985Z,
       'permissions.rolePermissions.updatedAt': 2018-07-18T06:13:29.985Z,
       'permissions.rolePermissions.roleId': 1,
       'permissions.rolePermissions.permissionId': 2 },
     { id: 1,
       name: 'anonymous',
       createdAt: 2018-07-18T06:13:29.971Z,
       updatedAt: 2018-07-18T06:13:29.971Z,
       'permissions.id': 10,
       'permissions.name': 'read-orgs',
       'permissions.createdAt': 2018-07-18T06:13:29.897Z,
       'permissions.updatedAt': 2018-07-18T06:13:29.897Z,
       'permissions.rolePermissions.createdAt': 2018-07-18T06:13:29.985Z,
       'permissions.rolePermissions.updatedAt': 2018-07-18T06:13:29.985Z,
       'permissions.rolePermissions.roleId': 1,
       'permissions.rolePermissions.permissionId': 10 },
     { id: 1,
       name: 'anonymous',
       createdAt: 2018-07-18T06:13:29.971Z,
       updatedAt: 2018-07-18T06:13:29.971Z,
       'permissions.id': 12,
       'permissions.name': 'read-supplies',
       'permissions.createdAt': 2018-07-18T06:13:29.898Z,
       'permissions.updatedAt': 2018-07-18T06:13:29.898Z,
       'permissions.rolePermissions.createdAt': 2018-07-18T06:13:29.985Z,
       'permissions.rolePermissions.updatedAt': 2018-07-18T06:13:29.985Z,
       'permissions.rolePermissions.roleId': 1,
       'permissions.rolePermissions.permissionId': 12 } ] }
```

So the request works but the structure of the output to me seems a little strange, I would expact that I would get back 1 array entry per role with an array of permissions inside it, instead I am getting a duplication of roles decided by the number of permissions that the user has. 

I would expect / prefer a structure more like this:
```js
{ total: 1,
  limit: 10,
  skip: 0,
  data: 
   [ { id: 1,
       name: 'anonymous',
       createdAt: 2018-07-18T06:13:29.971Z,
       updatedAt: 2018-07-18T06:13:29.971Z,
       permissionIds: [2, 10, 12] ] }
```

Are there any ways of doing this / suggestions on the best way to do this?

Thank you and regards,
Emir

**Comment by daffl** [comment]
Please see [the section about raw queries in the documentation](https://github.com/feathersjs-ecosystem/feathers-sequelize#sequelize-raw-queries). To get the include you expect you have to set `raw: false`.

**Comment by EmirGluhbegovic** [comment]
@daffl Thank you for the reply. I have followed the examples provided under the sections:
Working with **Sequelize Model instances** and  **sicruse/messages.hooks.js**
I cannot seem to get the output I seek. 

I have tried setting in the Before.Find hook rawfalse,
then in the after hook something like:
`function includeAssociated(context) {
  const sequelize = context.app.get('sequelizeClient');
  const { permissions } = sequelize.models;
  return hydrate({
    include: [permissions]
  }).call(this, context);
}`

I feel I must be doing something wrong but I am not sure at this point, I have tried a few variations.

**Comment by daffl** [comment]
What I mean is that all you have to do to get the nested models is updated you `attachAssociation` (which is a `before` hook) to:

```js
const attachAssociations = (context) => {
  // Get the Sequelize instance. In the generated application via:
  const sequelize = context.app.get('sequelizeClient');
  const { permissions } = sequelize.models;
  context.params.sequelize = {
    raw: false,
    include: [permissions]
  }
  return context;
}
```

**Comment by EmirGluhbegovic** [comment]
@daffl Thank you. That did the trick. I think the documentation could be a bit clearer about that. I dont mind adding to the documentation or writing an article as there have been a few hurdles in getting the setup correctly. Let me know what would be a better way, if wanted.

**Comment by daffl** [comment]
If you have an idea how it could be improved, a pull request is definitely welcome. Although the [docs for params.sequelize](https://github.com/feathersjs-ecosystem/feathers-sequelize#setting-paramssequelizeinclude) does mention that it should be done in a `before` hook. Maybe an example that shows the hook being registered might make it more clear.

Closing this issue since the problem has been solved.
