### ISSUE TITLE
Unhandled Rejection error

### ISSUE THREAD

**Issue by djadjabing** [feathersjs-ecosystem/feathers-sequelize#226]
### Steps to reproduce

I have create a new feathers application generated a connection (sequelize) for a mssql database.
I generate a service for this connection and after I start the application I got this message:

[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node src`
info: Feathers application started on http://localhost:3030
error: Unhandled Rejection at: Promise  {"_bitField":.......,"_fulfillmentHandler0":{}}

It must be in the part of the module... because I comment everything part by part. 

### Expected behavior
Just want only to start without do anything to see if its working.
### Actual behavior
Application won't start

### System configuration
Basic setup with a brand new feathers application

**Module versions** (especially the part that's not working):
@feathersjs/feathers: ^3.1.7
sequelize: ^4.37.6,

**NodeJS version**: v8.9.3

**Operating System**: Windows 10

**Browser Version**: Google Chrome

**React Native Version**:

**Module Loader**:

**Comment by DesignByOnyx** [comment]
Did you update the config file with a valid connection string? The generators will generate most of the connection string for you, but it's on you to make sure that it actually works. This is not a feathers thing - you have to do this with any application which uses a database.

Here's what feathers generates for you: 

> mysql://root:@localhost:3306/project_name

"project_name" is the name of your project and will vary depending on what your entered when you generated your project. The connection string above is missing the password, which is required whenever you install MySQL. Here's what the full connection string should look like:

> mysql://root:PASSWORD@localhost:3306/project_name

You can test your password my running this command:

```
mysql -u root -p
```

It will prompt you for a password, and if you don't remember your password you will need to reset it. You should follow instruction online for setting the MySQL root password, which is required for MySQL to work properly. Once you have you password, update your connection string and you should be good to go.

**Comment by djadjabing** [comment]
of course I do (I've used the generator from feathers) first was the problem with my DB password. The decodeURI sayed to me that there is a failure, I solved it with encodeURI my password and it seems to be working (I testet it in a browser)
