### ISSUE TITLE
Is there a way to createQuery?

### ISSUE THREAD

**Issue by EmirGluhbegovic** [feathersjs-ecosystem/feathers-sequelize#228]
Feathers-sequelize accepts the context.params.query and then in the background builds a sequelize query which gets executed.

I want to use the feathers params still but also add my own feathers where logic.

**Context.params.query**
`{ email: test@example.com, $limit: 1 }`

Looking at the following query:
```
context.params.sequelize = {
    raw: false,
    include: [{
      model: organisations,
      where: organisationId ? { id: organisationId } : undefined,
      include: [{
        model: roles,
        where: roleId ? { id: roleId } : undefined,
      }],
    }],
    where: single ? (
      sequelize.and(
        sequelize.where(
          sequelize.col('"organisations->organisation_users"."roleId"'),
          sequelize.col('"organisations->roles"."id"'),
        ),
        sequelize.where(
          sequelize.col('"organisations->organisation_users"."userId"'),
          sequelize.col("users.id")
        )
      )
    ) : undefined,
  }
```

Since I have defined my own where statement, it is overriding the one that feathers will make. I want to be able to merge them so my query and the feathers, limits, filters etc... continue to work as expected.

If someone has an alternative solution I am open. If there is a way to move my current sequelize where statements etc...

Thank you & Regards,
Emir

**Comment by daffl** [comment]
The functionality in https://github.com/feathersjs-ecosystem/feathers-sequelize/blob/master/lib/index.js#L42-L57 should indeed be extracted into its own class method so that it can be used when customizing the query.

**Comment by EmirGluhbegovic** [comment]
I guess that is a request for a pull-request to be made?

**Comment by daffl** [comment]
If you get to it before I do 😄 A `getQuery` method or something should do it and also be fairly easy to test.

**Comment by DesignByOnyx** [comment]
You can achieve what you want by updating the `context.params.query`. You do **not** want to pass a top-level "where" property in `context.params.sequelize`. Here is what the full code would look like:

```js
  context.params.sequelize = {
    /** DO NOT PASS A TOP-LEVEL "where" HERE **/
    raw: false,
    include: [{
      model: organisations,
      where: organisationId ? { id: organisationId } : undefined,
      include: [{
        model: roles,
        where: roleId ? { id: roleId } : undefined,
      }],
    }]
  }
  /** INSTEAD, UPDATE THE PARAMS.QUERY DIRECTLY **/
  if (single) {
    const orgUserRoleId = sequelize.col('"organisations->organisation_users"."roleId"');
    const orgUserUserId = sequelize.col('"organisations->organisation_users"."userId"');
    Object.assign(context.params.query, {
      [orgUserRoleId]: sequelize.col('"organisations->roles"."id"'),
      [orgUserUserId]: sequelize.col("users.id")
    });
  }
```

**Comment by EmirGluhbegovic** [comment]
@DesignByOnyx Thank you. @daffl 

I had to modify the code slightly to make it work as expected:

```
 if (single) {
    const orgUserRoleId = sequelize.col('"organisations->organisation_users"."roleId"');
    const orgUserUserId = sequelize.col('"organisations->organisation_users"."userId"');
    Object.assign(context.params.query, {
      [orgUserRoleId]: sequelize.and(
        sequelize.where(
          orgUserRoleId,
          sequelize.col('"organisations->roles"."id"')
        ),
        sequelize.where(
          orgUserUserId,
          sequelize.col("users.id")
        )
      )
    });
  }
```

The reason I have the single flag is that when I run find instead of get, so fetching many items instead of 1, I get an error` "missing FROM-clause entry for table \"organisations->organisation_users\""`
only when pagination is enabled, if I switch it off everything works as expected.

Any suggestions?

**Comment by DesignByOnyx** [comment]
If you can get your query working in isolation, we can help you integrate it into your hooks:

https://github.com/feathersjs-ecosystem/feathers-sequelize#testing-sequelize-queries-in-isolation

**Comment by EmirGluhbegovic** [comment]
@DesignByOnyx Thank you, will be doing that shortly!

**Comment by EmirGluhbegovic** [comment]
@DesignByOnyx Please view the sequelize query in isolation and let me know how to proceed:

```
// test.js
const app = require('./src/app');
// run setup to initialize relations
app.setup();
const seqClient = app.get('sequelizeClient');
const UsersModel = seqClient.models.users;
const OrgsModel = seqClient.models.organisations;
const RoleModel = seqClient.models.roles;
const log = console.log.bind(console);

const orgUserRoleId = seqClient.col('"organisations->organisation_users"."roleId"');
const orgUserUserId = seqClient.col('"organisations->organisation_users"."userId"');

UsersModel.findAll({
  /*
   * Build your custom query here. We will use this object later.
   */
  include: [{
    model: OrgsModel,
    where: { id: 1 },
    include: [{
      model: RoleModel,
      // where: { id: 4 },
    }],
  }],
  where: (
    seqClient.and(
      seqClient.where(
        orgUserRoleId,
        seqClient.col('"organisations->roles"."id"')
      ),
      seqClient.where(
        orgUserUserId,
        seqClient.col("users.id")
      )
    )
  )
}).then(log).catch(log);
```

**Comment by DesignByOnyx** [comment]
Sorry I'm just seeing this (I get too many github notifications... some fall through the cracks). Anyhow, if a before hook, you should be able do something like this:

```js
(context) => {
  if (!context.params.sequelize) context.params.sequelize = {};
  Object.assign(context.params.sequelize, {
    include: { /* copy the value for include here */ }
  });
  // for the WHERE clause, we want to update params.query
  Object.assign(context.params.query, seqClient.and( 
    /* copy code from above here */
  ));
  return context;
}
```
That should get you close. Hope that helps.
