### ISSUE TITLE
Valid password characters can break the connection string

### ISSUE THREAD

**Issue by Alfredo-Delgado** [feathersjs-ecosystem/feathers-sequelize#229]
### Steps to reproduce

In `./config/default.json`, set `postgres` to a connection string like `postgres://database_user:abc1d-e?=F$GhI2j@localhost:5432/target_database` and try to start the app.

### Expected behavior
Successful DB connection.

### Actual behavior
It seems that the connection string parsing in sequelize is brittle.

`error: Unhandled Rejection at: Promise  {"_bitField":18087936,"_fulfillmentHandler0":{"name":"SequelizeHostNotFoundError","parent":{"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"database_user","host":"database_user","port":5432},"original":{"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"database_user","host":"database_user","port":5432}}}      
`

### System configuration

**Module version**: feathers-sequelize@3.1.2
**NodeJS version**: v8.11.3
**Operating System**: macOS 10.13.6

I propose that we also accept an object like
```js
"postgres": {
  "host": "",
  "port": "",
  "username": "",
  "password": ""
  "database": ""
}
```

I guess this is something I could implement in the generators that output `default.json` and `src/sequelize.js`?

**Comment by Alfredo-Delgado** [comment]
I guess I should move this to https://github.com/feathersjs/generator-feathers, too.

**Comment by daffl** [comment]
Ref https://github.com/feathersjs/generator-feathers/issues/388 and https://github.com/feathersjs/feathers/issues/676

**Comment by EdDeAlmeidaJr** [comment]
I received this same error messa when I edited my **src/models/users.model.js** and described one of my fields as

```
    note: {
      type: DataTypes.TEXT**(256)**,
      allowNull: true
    }
```

It seems the fact I declared the size of the field wasn't well accepted by sequelize and the error message was 

> info: Feathers application started on http://localhost:3030
> error: Unhandled Rejection at: Promise  {"_bitField":18087936,"_fulfillmentHandler0":{}}

When I removed the (256) it worked fine again.

I hope this helps to bring some light to this issue.
