### ISSUE TITLE
Associations on Create

### ISSUE THREAD

**Issue by set321go** [feathersjs-ecosystem/feathers-sequelize#230]
### Steps to reproduce

I think there is a bit of a gap here between how sequelize describes how to do things and your documentation. I'm using the sequelize migrations to setup my schema, that seems to be working fine, the tables look ok and it looks like the foreign key column and constraint are created correctly.

The sequelize docs tell me I can use setX, getX & addX to associate models but this doesn't work because `context.data` does not appear to be a sequelize model in the before hooks. Your examples (and sequelize) using `include` are all query examples.

- Do I use include for creation? 
- Do i do the association in the after hook?
- Can i turn a `context.data` into a sequelize model in the before hook? Is this a good idea?

I have tried a lot of different variations so far but none work as expected. Here is an example of what i am trying to do. I am trying to model "Vendor hasMany Admins"

user.model
```
module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient');
  const user = sequelizeClient.define('user', {
    email: {
      type: DataTypes.STRING,
      unique: true
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false
    }
  }, {
    hooks: {
    }
  });

  user.associate = function (models) {
  };

  return user;
};
```

vendor.model
```
const Sequelize = require('sequelize');
const DataTypes = Sequelize.DataTypes;

module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient');
  const vendor = sequelizeClient.define('vendor', {
    name: {
      type: DataTypes.STRING,
      unique: true
    }
  }, {
    hooks: {
    }
  });

  vendor.associate = function (models) {
    vendor.hasMany(models.user, {as: 'Admins'});
  };

  return vendor;
};
```

vendor.hooks create (this doesn't work)
```
    create: [context => {
      context.data.admins = [parseInt(context.params.user._id, 10)];
    }],
```

**Comment by daffl** [comment]
This is my biggest issue with Sequelize. I still don't understand why it doesn't allow to create associations by id through the `data` object.

You can however set `raw: false` and call `context.result.setSomething` in an `after` hook.

**Comment by set321go** [comment]
Yeah coming from JPA Sequelize relations are a bit wierd. I'm most of the way there i think but still not getting the expected output, but maybe its not clear where things are being synchronous and where they are async.

my hooks now look like this 
before:
```
create: [context => {
      if (!context.params.sequelize) context.params.sequelize = {};
      Object.assign(context.params.sequelize, { raw: false });
    }],
```

after:
```
    create: [async context => {
      context.result.addAdmins([parseInt(context.params.user._id, 10)]);
    }, dehydrate()]
```

These hooks result in the data in the database looking correct but the output in my test does not include the associated object. I tried using include on dehydrate but looking at the code that does nothing.

should i refetch the data after adding the association or is there a more appropriate way of doing this?

**Comment by daffl** [comment]
This is another problem with Sequelize. You have to re-fetch the entry (unless `addAdmins` already returns it but I don't think so).

**Comment by set321go** [comment]
Thanks for all the help, still struggling to get to the finish here.

my after hooks now look like this
```
    create: [async context => {
      await context.result.addAdmins([parseInt(context.params.user._id, 10)]);
      context.result = await context.app.services.vendor.get(parseInt(context.result._id));
    }, dehydrate()],
```
From the logging 'it looks like' everything is executed in the correct order but when it comes doing the get it barfs saying `NotFound: No record found for id '1'` this would make sense if it is trying to load the data from the include table (the foreign key value should be 1) but it doesn't spit any sql out at this point so i can't see what query it tried to build

**Comment by set321go** [comment]
So the last part was my confusion with sequelize, the nclude should not be referencing the mode but the `association` like so `include: [{association: 'Admins'}]` or shorthand like `include: ['Admins']`. It is documented but its pretty well hidden. 

From a `feathers-sequelize` perspective i found the logging to be a problem debugging this. It was not clear to me what was going on when sequelize stopped spitting out sql statements, I ended up putting log messages into `index.js` to check what was being sent to sequelize.
