### ISSUE TITLE
How to use raw where clause

### ISSUE THREAD

**Issue by pramodlk** [feathersjs-ecosystem/feathers-sequelize#233]
I'm trying to figure out how to use raw where clause in feathers-sequelize

eg: 
`where TIME_TO_SEC(timediff(NOW(), last_viewed_at)) <=10`

Sequelize seems like support for that (https://github.com/sequelize/sequelize/issues/9410#issuecomment-387141567)

`{where: Sequelize.literal('your special where clause here') }`

How can we use this in feathers-sequelize ?

Thanks

**Comment by daffl** [comment]
This is what [params.sequelize](https://github.com/feathersjs-ecosystem/feathers-sequelize#paramssequelize) is intended to be used for.

**Comment by daffl** [comment]
What exactly is the problem then? Has you tried [testing the query in isolation](https://github.com/feathersjs-ecosystem/feathers-sequelize#testing-sequelize-queries-in-isolation)?

**Comment by pramodlk** [comment]
Finally i was able to get that working. Thanks. I'm posting the working code, it might help someone having same problem

```
const Sequelize = require('sequelize');
...
...
...

app.service('tickets').hooks({
  before: {
    find(context) {
      const sequelizeClient = context.app.get('sequelizeClient');
      const { Message, TicketView, TicketStatus, User } = sequelizeClient.models;
      var userId = context.params.query.userId;

      context.params.sequelize = {
	   raw: false, 
	   include: [
	          { 
	       	  model: TicketView , 
	       	  as: 'viewedBy', 
	       	  where: {user_id: { $not:  userId } },
	       	  include: [
	        		 { 
	       			  model: User, 
	       			  as: 'user'
	        		 }
		       	] 
		       },
		      { 
		  model: TicketStatus , 
		  as: 'lastResolvedStatus', 
	       	  where: Sequelize.literal('TIME_TO_SEC(timediff(NOW(), last_viewed_at)) <=10'),
		  include: [
	          	 { 
			  model: User, 
			  as: 'user'
			  }
		          ] 
		          },
		]
		};
	}
	}
  });
```
