### ISSUE TITLE
Include as array, no longer working

### ISSUE THREAD

**Issue by GioLogist** [feathersjs-ecosystem/feathers-sequelize#239]
### Expected behavior
The following code in readme, should work

```
      context.params.sequelize = {
         include: [{ model: AssociatedModel }]
      };
```

### Actual behavior
`Include unexpected. Element has to be either a Model, an Association or an object.`

Seems like it doesn't play well with arrays as per [_conformInclude](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L327)

### Workaround
The following 2 snippets work as expected:

```
      context.params.sequelize = {
         include: AssociatedModel
      };
```

```
      context.params.sequelize = {
        include: {
          model: AssociatedModel,
        },
      };
```

### System configuration

Sequelize version: 4.39.0
Feathers Sequelize: 3.1.2

**Comment by daffl** [comment]
I'm going to closes this since nothing in this adapter changed and is probably an issue with the underlying Sequelize version.
