### ISSUE TITLE
unable to select jsonb fields

### ISSUE THREAD

**Issue by jiangts** [feathersjs-ecosystem/feathers-sequelize#245]
I don't have a way to select only certain jsonb fields using the common feathers query syntax.

I know it's possible by setting custom attributes in `Model.findAll`. Is there a way we can access this query interface directly, like in the knex-adapter with `.createQuery`?

**Comment by daffl** [comment]
JSONB fields have to be selected by using [params.sequelize](https://github.com/feathersjs-ecosystem/feathers-sequelize#paramssequelize).
