### ISSUE TITLE
Multiple services, one transaction rollback

### ISSUE THREAD

**Issue by 1valdis** [feathersjs-ecosystem/feathers-sequelize#246]
### Steps to reproduce

Have a custom service, which on `create` calls `create` of two other services with a transaction in params.
```javascript
async create(data, params) {
    return Promise.all([
      this.options.app.service('firstService').create({
       //...
      }, {sequelize: params.sequelize}),
      this.options.app.service('secondService').create({
        //...
      }, {sequelize: params.sequelize}),
    ]);
  }
```
Throw an error in one of the called services, let's assume it's a validation error (I do it on before hook where my validation lies).

### Expected behavior
The transaction should be rejected and original validation error should be thrown and shown to the user.

### Actual behavior
Instead of original cause of transaction rollback, a `SequelizeDatabaseError: current transaction is aborted, commands ignored until end of transaction block` or `Transaction cannot be committed because it has been finished with state: rollback` is shown to the user.
How do I get and show an original validation error?

### System configuration
feathers-sequelize: 3.1.1
sequelize: 4.37.10

**Comment by 1valdis** [comment]
For now as a quick and dirty hack I have the error handler in those services being called:
```javascript
all: [(context) => {
      if (!context.error.message.startsWith('current transaction')) {
        throw context.error;
      }
    }],
```
Although I'm not sure how and why it works. It just works...

**Comment by daffl** [comment]
This might also mean that nobody is around that can help with this at the moment. Since it doesn't really seem to be specific to this adapter you might have more luck asking the question [in the Sequelize repository](https://github.com/sequelize/sequelize).
