### ISSUE TITLE
getModel() overriding with parameters broken in 4.0.x

### ISSUE THREAD

**Issue by AndrewJDR** [feathersjs-ecosystem/feathers-sequelize#261]
This is related to #234. I'll paste a relevant portion from that bug here:

> When a service call is made by some featherjs user's code, it's important to preserve the params object when making any subsequent service calls, as it's possible that the user of feathersjs intends to use these parameters as part of a getModel() override function in a custom service class (i.e. class MySpecialService extends Service with an overidden getModel()) For things like multi-tenancy schemes - hosting multiple domains/sites out of a single app instance such that each site needs to hit a different database. As far as I'm aware, a getModel() override is the best way of achieving that goal, and any practice of ignoring/clobbering the params passed in will cause problems for such a scheme.

It would appear that this way of doing things has been broken by some commits some time after aa969563fbe09af716ab60efa8a8918d25cf9d0e (basically, some of the recent 4.0 related commits)

I have prepared a set of tests of the getModel() + parameter passing solution mentioned above, and you can find these tests here:
https://github.com/AndrewJDR/feathers-sequelize/tree/add_tests_for_and_fix_getmodel_param_issues

Check out that branch and run `npm run coverage` to run the tests, which do pass. That is on a branch based on the pre-4.0 aa969563fbe09af716ab60efa8a8918d25cf9d0e commit.

If you cherry-pick that branches commits onto the current master commit a48604c287e7130c1891c3d54d95adc723e445e1 and fix the small merge issue, I've found that the tests no longer run at all :( PR #262 shows this test failure.

It appears that something has changed about the getModel() setup, with a .Model member sometimes being used instead of calling `getModel(params)`, which causes the overridden getModel() method to receive no params at all. (Edit: < That was just a theory, I'm actually not so sure that is why it's breaking). This could cause the overridden getModel() method to not be able to do the job it was intended to do, for example, handling a multi-tenancy situation by changing out to a different tenant's model (and thus db) depending upon certain parameters provided to `getModel()` (e.g. the host they're connecting to, or the ip address they're connecting from, etc), like mentioned above and in issue #234.

Any ideas on what we can do to address this? I looked over the 4.0 migration guide but i didn't see any alternatives/workarounds offered. Thanks.

**Comment by daffl** [comment]
Thanks for the detailed issue. I have a fix in https://github.com/feathersjs-ecosystem/feathers-sequelize/pull/263. The problem was the getter that basically caused a recursive call.
