### ISSUE TITLE
Incorrect Error Type

### ISSUE THREAD

**Issue by Sicria** [feathersjs-ecosystem/feathers-sequelize#269]
In #258 all errors are cast as ``NotFound`` when they should really be ``GeneralError`` since those types of errors can be caused from invalid types or strings which are too long.

For example, currently the error returns a stack of ``NotFound: value too long for type character varying(255)...``.

Thanks again for fixing the original issue, really appreciate it.

**Comment by daffl** [comment]
Closed via #275 and released as v5.0.0
