### ISSUE TITLE
Question: Multiple database connection

### ISSUE THREAD

**Issue by vinaykharecha** [feathersjs-ecosystem/feathers-sequelize#278]
Is it possible to add **multiple database** connection in **feathers sequelize**?
_i.e. pg and ms-sql_

**Comment by daffl** [comment]
Feathers and this adapter have no restriction on how many databases you can connect to. Just copy the `sequelize.js` file and change the names and initialization settings to the other database (e.g. `app.set('sequelizeClient', sequelize);` to `app.set('msClient', sequelize);`) and after generating a Sequelize service, point the `sequelize` instance to `app.get('msClient')`.

**Comment by vinaykharecha** [comment]
@daffl, Perfect! it worked
Thanks for your quick response and contribution; i really appreciate it. 🙂
_PS: closing this issue._
