### ISSUE TITLE
include association's association

### ISSUE THREAD

**Issue by JackyW83** [feathersjs-ecosystem/feathers-sequelize#284]
I'm trying to include association's object,
say, we have _transaction_item_ model belongs to _transaction_ which in turn belongs to a _user_ object,
I attempted to include user in _transaction_item_ hook like   
`include: ['transaction.user']` 
but it throw 'Association with alias \"transaction.student\" does not exists' error.
please hint me if it's possible to implement. 
thank you

**Comment by ccummings** [comment]
This is covered in the Sequalize docs, [Nested eager loading](https://sequelize.readthedocs.io/en/latest/docs/models-usage/index.html#nested-eager-loading).

**Comment by JackyW83** [comment]
thanks
