### ISSUE TITLE
$iLike operator declared incorrectly in default operators

### ISSUE THREAD

**Issue by DaddyWarbucks** [feathersjs-ecosystem/feathers-sequelize#290]
`feathers-sequelize` version: 5.1.1
`sequelize` version: 4.43.0

I believe this file has a typo: https://github.com/feathersjs-ecosystem/feathers-sequelize/blob/9db35f5ef1f63aa57947fb3ee11ddceda74f1a78/lib/index.js#L18
It should be `Op.iLike` with a capital `L` as per  http://docs.sequelizejs.com/manual/querying.html#operators

<img width="1920" alt="Screen Shot 2019-04-16 at 10 09 22 PM (2)" src="https://user-images.githubusercontent.com/4671808/56304417-b28ea600-6103-11e9-8094-6096bdd8aa4c.png">

**Comment by daffl** [comment]
Closed via #291
