### ISSUE TITLE
Warning When Starting Feathers when using Sequelize 5.10.0 with feathers-sequelize 5.1.3

### ISSUE THREAD

**Issue by frastlin** [feathersjs-ecosystem/feathers-sequelize#305]
### Steps to reproduce

I installed the latest feathers-sequelize and the latest sequelize. When I do "npm start", I get the following message:

```
> node src/

(node:3147255) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
```

### Expected behavior

Nothing should show as a warning.

### Actual behavior
The error shows

### System configuration

Sequelize: 5.10.0
feathers-sequelize: 5.1.3

### Fix

Just delete the line from the feathers generator that says:

```
    operatorsAliases: false,
```

**Comment by edwardsmarkf** [comment]
is it better to change to:

operatorsAliases: null,

instead of false?

interesting the documentation still says "false":

http://docs.sequelizejs.com/manual/querying.html

thank you for identifying this issue.   there is a similar situation on
'logging: true'"


Thank you,

Mark Edwards

**Comment by daffl** [comment]
Don't be afraid to touch the code. Just remove `operatorAliases` as the message suggests. The latest CLI has been updated accordingly.
