### ISSUE TITLE
sequelize db:migrate does not create initial tables defined in feathersjs app model

### ISSUE THREAD

**Issue by sbsujith** [feathersjs-ecosystem/feathers-sequelize#310]
### Steps to reproduce
1. Setup the sequelize migration in a working feathersjs app as explained in the instruction. 
2. Add a migration file to modify the table. 
3. Configure package.json with `"start": "sequelize db:migrate && node src/"`

### Expected behavior
When clean `npm start`, expect to run the migration, including creating the initial db tables and its association defined in the application model files, and then to start the application.

### Actual behavior
Shows the below error:
ERROR: Table 'xxxxx.roles' doesn't exist
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxxxx@0.0.0 start: `sequelize db:migrate && node src/`
npm ERR! Exit status 1

This means the application start did not create the initial table schema defined in the application model files in src/models/ folder. I think I am missing something that binds migration with application.

Note: Application creates the initial tables and association when run without migration, though. Migration also completes successfully when run after the tables are created. But can't run the migration and the application in a single go.

### System configuration

**Module versions** (especially the part that's not working):

DB: MySQL

"@feathersjs/feathers": "^3.3.1"
"feathers-sequelize": "^4.1.1"

--------------------
**app.js:**
```
const path = require('path');
const favicon = require('serve-favicon');
const compress = require('compression');
const helmet = require('helmet');
const cors = require('cors');
const logger = require('./logger');

const feathers = require('@feathersjs/feathers');
const configuration = require('@feathersjs/configuration');
const express = require('@feathersjs/express');
const socketio = require('@feathersjs/socketio');


const middleware = require('./middleware');
const services = require('./services');
const appHooks = require('./app.hooks');
const channels = require('./channels');

const sequelize = require('./sequelize');

const authentication = require('./authentication');

const app = express(feathers());

// Load app configuration
app.configure(configuration());
// Enable security, CORS, compression, favicon and body parsing
app.use(helmet());
app.use(cors());
app.use(compress());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(favicon(path.join(app.get('public'), 'favicon.ico')));
// Host the public folder
app.use('/', express.static(app.get('public')));

// Set up Plugins and providers
app.configure(express.rest());
app.configure(socketio());

app.configure(sequelize);

// Configure other middleware (see `middleware/index.js`)
app.configure(middleware);
app.configure(authentication);
// Set up our services (see `services/index.js`)
app.configure(services);
// Set up event channels (see channels.js)
app.configure(channels);

// Configure a middleware for 404s and the error handler
app.use(express.notFound());
app.use(express.errorHandler({ logger }));

app.hooks(appHooks);

module.exports = app;
```

**sequelize.js:**
```
const Sequelize = require("sequelize");

module.exports = function(app) {
  const connectionString = app.get("mysql");
  const sequelize = new Sequelize(connectionString, {
    dialect: "mysql",
    logging: true,
    operatorsAliases: false,
    define: {
      freezeTableName: true,
      timestamps: false
    }
  });
  const oldSetup = app.setup;

  app.set("sequelizeClient", sequelize);

  app.setup = function(...args) {
    const result = oldSetup.apply(this, args);

    // Set up data relationships
    const models = sequelize.models;
    Object.keys(models).forEach(name => {
      if ("associate" in models[name]) {
        models[name].associate(models);
      }
    });

    // Sync to the database
    sequelize.sync();

    return result;
  };
};
```

**migrations/config.js:**
```
const app = require("../src/app");
const env = process.env.NODE_ENV || "development";
const dialect = "mysql";

module.exports = {
  [env]: {
    dialect,
    url: app.get(dialect),
    migrationStorageTableName: "_migrations",
    seederStorage: "sequelize",
    seederStorageTableName: "_migrations_seed"
  }
};
```

**migrations/models.js:**
```
const Sequelize = require("sequelize");
const app = require("../src/app");
const sequelize = app.get("sequelizeClient");
const models = sequelize.models;

// The export object must be a dictionary of model names -> models
// It must also include sequelize (instance) and Sequelize (constructor) properties
module.exports = Object.assign(
  {
    Sequelize,
    sequelize
  },
  models
);
```
Thanks in advance;
@daffl

**Comment by daffl** [comment]
The migration expects the tables to exist. I don't recommend to run migrations with the start script, they are meant to be run separately.

**Comment by sbsujith** [comment]
@dffl Thank you for the prompt response. 
I am bit confused with the feathers integration with sequelize.

- If the migration expects tables to exist by running the application beforehand (is there any other way to create tables?), how does it playout in production considering the db user role should have the table schema creation privilege as well -  which is not ideal, or should we switch between different db user roles?

- If I want to make any schema change from the initial table definition, I should be making it in related migration script. Should I be making the same change in the app model definition as well? If so that would be a overkill.

- Considering the execution sequence of schema definition, seeding and migrations are related to each other, is there a best practice on these to feathersjs application?

As always, 
Thanks is advance.

**Comment by daffl** [comment]
You can change `sequelize.sync();` to `app.set('sequelizeSync', sequelize.sync());` and then in a migration do

```js
const app = require('../src/app');

const setupApplication = async () => {
  app.setup();
  return app.get('sequelizeSync');
};

module.exports = {
  async up () {
    await setupDb();
    // Do things here
  },

  async down () {
    await setupDb();
    // Do things here
  }
};
```

**Comment by sbsujith** [comment]
Thanks @daffl.
If I understand correctly this is what you try to explain; when `db:migrate` is  called that would create the app and create all the pending tables based on app models, and then run all the pending migrations to make the db in sync. Thats what I want and would work for me in production as well.

However I am not sure where in migration to put the second part of your code snippet that wire migration with the app (sorry I am new to sequelize and feathersjs). 

I have config.js and model.js (contents in previous post) in /migration folder, apart from /scripts and /seeders. So where should I be putting your code to invoke when migration is run? Also where does the method setupDb() come from?
Thanks again for your timely help.

**Comment by sbsujith** [comment]
@daffl , Could you please help on this.
Thanks
