### ISSUE TITLE
Creating a Test Environment?

### ISSUE THREAD

**Issue by frastlin** [feathersjs-ecosystem/feathers-sequelize#314]
Hello,
I would like to see a section in the readme about creating a test environment. There is documentation on [writing tests with Feathers,]( https://docs.feathersjs.com/guides/chat/testing.html) but the database section only tells how to do tests with nedb, witch is much different than with Sequelize. Here are my questions:

1.	How do I clean all the services every time?
2.	How do I keep migrations the same across both the test and main DB?
3.	Are there any oddities that I should be aware of when testing Sequelize services?

Thank you,

**Comment by daffl** [comment]
As described in the [Feathers configuration API](https://docs.feathersjs.com/api/configuration.html), create a file in `config/test.json` and set the properties (e.g. connection string) you need. Then run your tests with the environment variable `NODE_ENV=test` set.

**Comment by frastlin** [comment]
This is perfect! I would add that the clean command should be:

    "clean": "NODE_ENV=test node cleanTestDb.js",

It would be amazing if this was in the readme.

**Comment by daffl** [comment]
I forgot to mention that this needs a `sequelizeSync` set as it has been recently added to the generator in https://github.com/feathersjs/generator-feathers/pull/458/files#diff-0b2f9bcefdb2923ff25ba4f1f5ac4da3R40

Still debating if it should even be part of the generated application anyway. This is probably the kind of setup you'd want.

**Comment by frastlin** [comment]
I don't know if this is related to Sequelize, but when I run jest test/app.test/js, jest does not exit. It says:


Ran all test suites matching /test\/app.test.js/i.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with
 `--detectOpenHandles` to troubleshoot this issue.

Then when I run again with --detectOpenHandles, I get:

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  DNSCHANNEL

      at dns.js:338:23
Thanks,

**Comment by frastlin** [comment]
I have another problem:
When I run a create method on the DB after running the above clean function, I get the following error:
    error: GeneralError: relation "customers" does not exist
The only way to fix this is to start the server first, close the server, then run the test scripts. I'm guessing it has something to do with the fact the Postgress DB takes a while to create the tables. I tried setting a setTimeout function, but that didn't work for some reason.
Any ideas on how to fix this?
