### ISSUE TITLE
Eagerly return associations of Create 

### ISSUE THREAD

**Issue by rxb** [feathersjs-ecosystem/feathers-sequelize#327]
### Steps to reproduce
Set up model with associations
Set up `before` `all` hook to eagerly include associations. Ex:
```
(context) => {
    const sequelize = context.app.get('sequelizeClient');
    const { users } = sequelize.models;
    context.params.sequelize = {
        include: [ users ]
    };
    return context;
}
````
Associations are returned wonderfully in `get` and `find` calls, but not `create`

Tried researching this issue, but I'm still not 100% if this issue would count as a feature request, a bug report, or if I'm just doing something wrong here. Thanks for your help!

**Comment by daffl** [comment]
I know it's pretty weird but apparently that's not possible even with Sequelize itself. If you want associations in a create an after hook with something like `context.result = context.service.get(context.result.id, params);` needs to be used.

**Comment by rxb** [comment]
Thanks! That would have have taken me forever to figure out on my own. For future searchers, I'll post here the after hook that I ended up using in my project:

```
create: [
      async (context) => {
        context.result = await context.app.service('comments').get(context.result.id, context.params);
        return context
      },
    ],
```

**Comment by edwardsmarkf** [comment]
should this be included as a recipe?

Thank you,

Mark Edwards
