### ISSUE TITLE
Should the foreign key be automatially created when executing hasmany?

### ISSUE THREAD

**Issue by jbatx** [feathersjs-ecosystem/feathers-sequelize#351]
I've added a has many relationship to my groups model like this
`groups.hasMany(models.roles)`

I was expecting it to create the foreign key in roles when I restarted the app.  It didn't appear to do anything at all - there's no foreign key.   

Is that by design?   Is it expected that I need to manually create a migration to add the foreign key?

When I created a many-to-many and restarted the app, the 'through' table was automatically created.   Hence my confusion about what to expect.

**Comment by xavierbol** [comment]
Hello @jbatx 

Normally, the foreign is automatically created in your *roles* model.

However in the documentation in the sequelize website, to create an association One-to-Many between your *roles* model and *groups* (where the *roles* table must have the foreign key), you need to add in your *roles* model an association like this : `roles.belongsTo(models.groups)`. I don't know if it's the case in your code.

You can find the documentation [here](https://sequelize.org/master/manual/assocs.html#creating-the-standard-relationships).
