### ISSUE TITLE
Getting issue with sequelize migration

### ISSUE THREAD

**Issue by kikusourabh** [feathersjs-ecosystem/feathers-sequelize#360]
Hi, I'm trying to setup this feathers js app by **feathers generate app** command and after all setting up app it was working fine with initial setup and I tried the [Migrations](https://github.com/feathersjs-ecosystem/feathers-sequelize#migrations) steps given in this repo readme. after all done I'm stuck with this error logs

This is my config.js file
```
const app = require("../../src/app");
const env = process.env.NODE_ENV || "default";
const dialect = "mysql";

module.exports = {
  [env]: {
    dialect,
    url: app.get(dialect),
    migrationStorageTableName: "_migrations",
  },
};
```

This is my .sequelizerc 

```
const path = require('path');

module.exports = {
  'config': path.resolve('migrations/config/config.js'),
  'migrations-path': path.resolve('migrations'),
  'seeders-path': path.resolve('migrations/seeders'),
  'models-path': path.resolve('migrations/models')
};

```
The app is in src/app, so when I try to run sequelize db:migrate it will show this error log
```
Sequelize CLI [Node: 14.8.0, CLI: 6.2.0, ORM: 6.3.5]

ERROR: Error reading "migrations\config\config.js". Error: Error: Cannot find module '../../src/app'
Require stack:
- D:\work\office-backend\migrations\config\config.js
- C:\Users\karma\AppData\Roaming\npm\node_modules\sequelize-cli\lib\helpers\config-helper.js
- C:\Users\karma\AppData\Roaming\npm\node_modules\sequelize-cli\lib\helpers\index.js
- C:\Users\karma\AppData\Roaming\npm\node_modules\sequelize-cli\lib\commands\init.js
- C:\Users\karma\AppData\Roaming\npm\node_modules\sequelize-cli\lib\sequelize
```
OS: windows 10,
Node: v14.8.0
Npm: 6.14.10

Can someone help me with this from your team? looking forward for the response, Thank you.

**Comment by MarcGodard** [comment]
`../../src/app` -> `'../src/app'`

**Comment by Konstantine899** [comment]
Can someone help me with this from your team? looking forward for the response, Thank you.
