### ISSUE TITLE
Allow join queries on remove

### ISSUE THREAD

**Issue by DaddyWarbucks** [feathersjs-ecosystem/feathers-sequelize#402]
Unfortunately the Sequelize `Model.destroy` method does not allow an `include` option. The `include` option is generally used to make join queries that allow the user to query/populate across tables. And it makes some sense why Sequelize would do that, its trying to handle cascades, truncates, paranoid, etc.
But, this library is already making some abstractions above this like `$returning`, etc. I would like to update the `_remove` method to use the `idList` approach found in the `_patch` method.

**Comment by fratzinger** [comment]
resolved in #403
