### ISSUE TITLE
Since version 6.4.0 getting "error: GeneralError: column "id" does not exist"

### ISSUE THREAD

**Issue by MarcGodard** [feathersjs-ecosystem/feathers-sequelize#406]
### Steps to reproduce

Update to version 6.4.0 and have a many to many table that doesn't use an `id` column.

### Expected behavior

To work?

### Actual behavior

Error, looking for `id` column

### System configuration

N/A

**Comment by DaddyWarbucks** [comment]
We hashed this out over in the Discord channel. All tables require a primary key. This will be noted in the README for V7.
