### ISSUE TITLE
Error while making a PATCH method call

### ISSUE THREAD

**Issue by subodhpareek18** [feathersjs-ecosystem/feathers-sequelize#87]
I was looking to send atomic updates to my server and in doing so required a `PATCH` call to be made. But the server returned the following error to the client (with `errorhandler` on).
```js
{
  "name": "GeneralError",
  "message": "column \"id\" does not exist",
  "code": 500,
  "className": "general-error",
  "data": {},
  "errors": {}
}
```
Without `errorhandler` this was the error printed on the server console.
```
SequelizeBaseError: column "id" does not exist                                                                                     
    at Query.formatError (D:\code\playground\core-playground\feathers\node_modules\sequelize\lib\dialects\postgres\query.js:357:14)
    at Query.<anonymous> (D:\code\playground\core-playground\feathers\node_modules\sequelize\lib\dialects\postgres\query.js:88:19) 
```
Now I was able to make `GET` `PUT` calls to the server no problem. But it's only during `PATCH` is when I'm facing this issue. And I am a bit confused sue to that reason, because `PUT` must take similar arguments as `PATCH`.

Any way to diagnose it further?

One possibility is that my primary key in the resource is not named `id` rather custom named as `xyz_id`, if this is the issue in fact then any way I can use a hook to pre-process the data and make the patch method work? And also shouldn't this simply work out of the box given the `id` is already present in the URL to which the call is made `/db/:resource/:id` and there should be no reliance on the primary key being named `id`.

**Comment by zusamann** [comment]
Ok the above is indeed the issue, while setting up the model need to specify the custom primary key, which I did as so.
```js
  Object.keys(db.sequelize.models)
    .map(key => {
      app.use(`/db/${key}`, sequelize({
        Model: db[key],
        paginate: {
          default: 10,
          max: 25
        },
        id: `${key}_id`
      }));
```
Since this such a hard requirement, I have a small suggestion to make. 

While setting up the service it should throw an error when an `id` field is not passed. Forcing the user to pass the key.  The other option is to not rely on this at all, since the sequelize model will already contain the `primaryKey` bool next to the intended field, should try and use that if possible.

Furthermore I'd like to understand why this works for `PUT` without needing the custom key but not for `PATCH` and `GET` or any other method.

**Comment by daffl** [comment]
I think the reason is that `get`, `update` and `remove` use `findById` where `patch` does not. We'll need a way to get the name of the primary key field from the model and then use that for `patch` as well.

**Comment by zusamann** [comment]
Can use `findById` for `patch` as well, we already have the `id` in the url while making the call, `db/:resource/:id` is there a scenario where you think the `id` will not be present?

**Comment by daffl** [comment]
Yes, id can be `null` if you are updating multiple records. You can do things like `PATCH /endpoint?completed=true`.

**Comment by zusamann** [comment]
And is this not applicable to `put`?

**Comment by daffl** [comment]
Feathers does allow it but the database adapters don't. Doing a multi `PUT` (`update`) which replaces the entire list of resources with a single new one doesn't make much sense.

**Comment by zusamann** [comment]
Ok, I'll close the issue, though I hope the above edge case can be documented somewhere.

**Comment by daffl** [comment]
I still think using the primary key of the model as the `id` property by default is a valuable change. So let's keep this open.

**Comment by hubgit** [comment]
I hit this same issue today, and was able to fix it by adding `id: 'uuid'` to the service options as described above. I wouldn't have been able to work that out without having found this issue, so it would be great if `patch` worked in the same way as the other methods and automatically used the primary key as the id field when it's specified.

**Comment by Dahkenangnon** [comment]
Just if it can help someone.

I was faced to this error but when tracking it i realize that the id i was passing to app.service('any_service').get(id,{}) or 
app.service('any_service').patch(id,{}) were undefined.

So when i found what were causing the undefined id, it works well.
So i recommend you to check if you're not passing a null id.

Thank
